#%RAML 1.0 NamedExample
example: |
  [
                  {
                    "loan_id": "PERSONAL_1234",
                    "loan_amount": 20000,
                    "tenure": 60,
                    "interest": 8
                  },
                  {
                    "loan_id": "PERSONAL_5678",
                    "loan_amount": 30000,
                    "tenure": 40,
                    "interest": 7
                  }
                ]